version: '3.7'

services:
  trackmania:
    image: trackmania
    container_name: trackmania
    build: .
    volumes:
      - trackmania_db:/var/lib/mysql
    ports:
      - 5000:5000/tcp
      - 2350:2350/tcp
      - 2350:2350/udp
      - 3450:3450/tcp
      - 3306:3306
      - 8080:80

volumes:
  trackmania_db:

networks:
  default:
    external:
      name: trackmania_network
