version: '3.7'

services:
  trackmania:
    image: trackmania
    container_name: trackmania
    build: .
    network_mode: 'host'
    volumes:
      - .:/app
    ports:
      - 5000:5000
      - 2350:2350
      - 3450:3450
