version: '3.7'

services:
  trackmania:
    image: trackmania
    container_name: trackmania
    build: .
    volumes:
      - .:/app
    ports:
      - 5000-5010:5000-5010
      - 2350-2360:2350-2360
      - 3450-3460:3450-3460
